# Generated by Django 5.0.3 on 2026-01-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0010_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
