# Generated by Django 5.0.3 on 2026-01-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0011_remove_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
    ]
